#!/usr/bin/env python3

import os
import sys
import requests
import re


########## GLOBALS ##########

URL = "https://www.zipcodestogo.com/Florida/"
SIZES = []


########## FUNCTIONS ##########

def usage(exit_code=0):
	print('''Usage: {} [OPTIONS] # # # # ...
	-h HELP  Display usage message
	-u URL   Specify the URL to look at
	# SIZE   Number of characters in each word (can be 1 or more words)
	'''.format(os.path.basename(sys.argv[0])))
	sys.exit(exit_code)

def getRegex(sizes=SIZES):
	regex = "[\s\W]"
	for index, size in enumerate(sizes, 1):
		if index != len(sizes):
			regex = regex + "([0-9A-Za-z]" + "{" + str(size) + "})[\s]+"
		else:
			regex = regex + "([0-9A-Za-z]" + "{" + str(size) + "})[\s\W]+"
	return regex

def getMatches(url=URL, sizes=SIZES):
	response = requests.get(url).text
	regex = getRegex(sizes)
	matches = set(re.findall(regex, response))
	printHeader(sizes)
	printMatches(matches)

def printHeader(sizes=SIZES):
	print()
	for size in sizes:
		head = '-'*size
		print("{} ".format(head), end='')
	print()

def printMatches(matches):
	for match in matches:
		for word in match:
			print("'{}' ".format(word), end='')
		print()
	print()

########## PARSE COMMAND-LINE ARGUMENTS ##########

args = sys.argv[1:]
while len(args) and args[0].startswith('-') and len(args[0]) > 1:
	arg = args.pop(0)
	if arg == '-h':
		usage(0)
	elif arg == '-u':
		URL = args.pop(0)
	else:
		usage(1)

while len(args):
	size = args.pop(0)
	SIZES.append(int(size))

########## PERFORM OPERATIONS ##########

getMatches(URL, SIZES)

